type User @table {
  displayName: String!
  createdAt: Timestamp!
  email: String
  profilePictureUrl: String
  bio: String
}

type BlogPost @table {
  title: String!
  content: String!
  createdAt: Timestamp!
  updatedAt: Timestamp!
  isPublic: Boolean!
  author: User
  tags: [String]
}

type Comment @table {
  content: String!
  createdAt: Timestamp!
  author: User
  blogPost: BlogPost
}

type Favorite @table(key: ["user", "blogPost"]) {
  createdAt: Timestamp!
  user: User!
  blogPost: BlogPost!
}

type Tag @table {
  name: String!
  description: String
}